# Generated by Django 4.2.13 on 2024-05-21 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_overview_movie_runtime_movie_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='color',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
